config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :recipes
  root "recipes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/direction.rb
class Direction < ApplicationRecord
  belongs_to :recipe
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  
  has_many :ingredients, inverse_of: :recipe
  has_many :directions, inverse_of: :recipe

  accepts_nested_attributes_for :ingredients, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :directions, reject_if: :all_blank, allow_destroy: true

  validates :title, :description, :image, presence: true

  has_attached_file :image, styles: { medium: "400x400>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :find_recipe, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @recipes = Recipe.all.order("created_at DESC")
  end

  def show
  end

  def new
    @recipe = current_user.recipes.build
  end

  def create
    @recipe = current_user.recipes.build(recipe_params)
    if @recipe.save
      redirect_to @recipe, notice: "建立了新食譜"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @recipe.update(recipe_params)
      redirect_to @recipe, notice: "更新成功"
    else
      render 'edit'
    end
  end

  def destroy
    @recipe.destroy
    redirect_to root_path, notice: "刪除成功"
  end
  private
    def find_recipe
      @recipe = Recipe.find(params[:id])
    end

    def recipe_params
      params.require(:recipe).permit(:title, :description, :image, ingredients_attributes: [:id, :name, :_destroy], directions_attributes: [:id, :step, :_destroy])
    end

    def correct_user
      redirect_to root_path, notice: "你沒有權限" unless @recipe.user == current_user
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Recipe App
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    %nav.navbar.navbar-default
      .container
        .navbar-brand= link_to "Recipe App", root_path
        - if user_signed_in?
          %ul.nav.navbar-nav.navbar-right
            %li= link_to "新食譜", new_recipe_path
            %li= link_to "登出", destroy_user_session_path, method: :delete
        - else
          %ul.nav.navbar-nav.navbar-right
            %li= link_to "註冊", new_user_registration_path
            %li= link_to "登入", new_user_session_path
    .container
      - flash.each do |name, msg|
        = content_tag :div, msg, class: "alert"

      = yield

app/views/recipes/_direction_fields.html.haml
.form_inline.clearfx
  .nested-fields
    = f.input :step, input_html: { class: "form-input form-control"}
    = link_to_remove_association "刪除", f, class: "btn btn-defult"

app/views/recipes/_form.html.haml
= simple_form_for @recipe, html: { multipart: true } do |f|
  - if @recipe.errors.any?
    #errors
      %p
        = @recipe.errors.count
      %ul
        - @recipe.errors.full_messages.each do |msg|
          %li = msg
  .panel-body
    = f.input :title, label: '標題', input_html: { class: 'form-control'}
    = f.input :description,label: '描述', input_html: { class: 'form-control'}
    = f.input :image, label: '圖片', input_html: { class: 'form-control'}

    .row
      .col-md-6
        %h3 材料
        #ingredients
          = f.simple_fields_for :ingredients do |ingredient|
            = render 'ingredient_fields', f: ingredient
          .link
            = link_to_add_association "新增材料", f, :ingredients, class: "btn btn-default"
      .col-md-6
        %h3 作法
        #directions
          = f.simple_fields_for :directions do |direction|
            = render 'direction_fields', f: direction
          .link
            = link_to_add_association "新增作法", f, :directions, class: "btn btn-default"

  = f.button :submit, yield(:button_text) , class: "btn btn-priary"

app/views/recipes/_ingredient_fields.html.haml
.form_inline.clearfx
  .nested-fields
    = f.input :name, input_html: { class: "form-input form-control"}
    = link_to_remove_association "刪除", f, class: "btn btn-defult"

app/views/recipes/edit.html.haml
- provide(:button_text, "修改食譜")
%h1 修改食譜

= render 'form'

%br/

app/views/recipes/index.html.haml
- @recipes.each_slice(3) do |recipes|
  .row
    -recipes.each do |recipe|
      .col-md-4
        .recipe
          .image_wrapper
            = link_to recipe do
              = image_tag recipe.image.url(:medium)
          %h2= link_to recipe.title, recipe

app/views/recipes/new.html.haml
- provide(:button_text, "建立食譜")
%h1 新食譜

= render 'form'

%br/

= link_to "回首頁", root_path, class: "btn btn-default"

app/views/recipes/show.html.haml
.main_contain
  #recipe_top.row
    .col-md-4
      = image_tag @recipe.image.url(:medium, class: "recipe_image")
    .col-md-8
      #recipe_info
        %p.description= @recipe.description
        %p
          這篇食譜有由
          = @recipe.user.email
          製作!

  .row
    .col-md-6
      #ingredients
        %h2 食材
        - @recipe.ingredients.each do |ingredient|
          %ul
            %li= ingredient.name
    .col-md-6
      #directions
        %h2 步驟
        - @recipe.directions.each do |direction|
          %ul
            %li= direction.step

  .row
    .col-md-12
      =link_to "回首頁", root_path, class: "btn btn-default"
      - if user_signed_in? && @recipe.user == current_user
        =link_to "修改", edit_recipe_path, class: "btn btn-default"
        =link_to "刪除", recipe_path, method: :delete, data: {confirm: "確定刪除嗎？"}, class: "btn btn-danger"